export const DataProduct = [
    {
        id: 1,
        name: 'Playera Rick and Morty',
        color: 'Blanco y Negro',
        href: '/404',
        imageSrc: '/shop/image1.webp',
        imageAlt: 'Playera Rick and Morty',
        price: '$250',
    },
    {
        id: 2,
        name: 'Playera Star Wars',
        color: 'Negro',
        href: '/405',
        imageSrc: '/shop/imagen2.webp',
        imageAlt: 'Playera Star Wars',
        price: '$200',
    },
    {
        id: 3,
        name: 'Sudadera Marvel',
        color: 'Azul',
        href: '/406',
        imageSrc: '/shop/imagen3.webp',
        imageAlt: 'Sudadera Marvel',
        price: '$350',
    },
    {
        id: 4,
        name: 'Gorra Batman',
        color: 'Negro',
        href: '/407',
        imageSrc: '/shop/imagen4.webp',
        imageAlt: 'Gorra Batman',
        price: '$150',
    },
    {
        id: 5,
        name: 'Calcetines Superman',
        color: 'Rojo',
        href: '/408',
        imageSrc: '/shop/imagen5.webp',
        imageAlt: 'Calcetines Superman',
        price: '$50',
    },
    {
        id: 6,
        name: 'Mochila Harry Potter',
        color: 'Gris',
        href: '/409',
        imageSrc: '/shop/imagen6.webp',
        imageAlt: 'Mochila Harry Potter',
        price: '$300',
    },
    {
        id: 7,
        name: 'Pendientes Zelda',
        color: 'Dorado',
        href: '/410',
        imageSrc: '/shop/imagen7.webp',
        imageAlt: 'Pendientes Zelda',
        price: '$80',
    },
    {
        id: 8,
        name: 'Bufanda Doctor Who',
        color: 'Azul',
        href: '/411',
        imageSrc: '/shop/imagen8.webp',
        imageAlt: 'Bufanda Doctor Who',
        price: '$120',
    },
    {
        id: 9,
        name: 'Taza Pokémon',
        color: 'Amarillo',
        href: '/412',
        imageSrc: '/shop/imagen9.webp',
        imageAlt: 'Taza Pokémon',
        price: '$15',
    },
    {
        id: 10,
        name: 'Llavero Mario Bros',
        color: 'Multicolor',
        href: '/413',
        imageSrc: '/shop/imagen10.webp',
        imageAlt: 'Llavero Mario Bros',
        price: '$10',
    },
    {
        id: 11,
        name: 'Playera Iron Man',
        color: 'Rojo',
        href: '/414',
        imageSrc: '/shop/imagen11.webp',
        imageAlt: 'Playera Iron Man',
        price: '$220',
    },
    {
        id: 12,
        name: 'Gorra Pokémon',
        color: 'Azul',
        href: '/415',
        imageSrc: '/shop/imagen12.webp',
        imageAlt: 'Gorra Pokémon',
        price: '$180',
    },
    {
        id: 13,
        name: 'Calcetines Batman',
        color: 'Negro',
        href: '/416',
        imageSrc: '/shop/imagen31.webp',
        imageAlt: 'Calcetines Batman',
        price: '$60',
    },
    {
        id: 14,
        name: 'Mochila Star Trek',
        color: 'Negro',
        href: '/417',
        imageSrc: '/shop/imagen32.webp',
        imageAlt: 'Mochila Star Trek',
        price: '$280',
    },
    {
        id: 15,
        name: 'Pendientes Star Wars',
        color: 'Plateado',
        href: '/418',
        imageSrc: '/shop/imagen15.webp',
        imageAlt: 'Pendientes Star Wars',
        price: '$90',
    },
    {
        id: 16,
        name: 'Bufanda Harry Potter',
        color: 'Gris',
        href: '/419',
        imageSrc: '/shop/imagen16.webp',
        imageAlt: 'Bufanda Harry Potter',
        price: '$130',
    },
    {
        id: 17,
        name: 'Taza The Avengers',
        color: 'Negro',
        href: '/420',
        imageSrc: '/shop/imagen17.webp',
        imageAlt: 'Taza The Avengers',
        price: '$20',
    },
    {
        id: 18,
        name: 'Llavero Superman',
        color: 'Azul',
        href: '/421',
        imageSrc: '/shop/imagen18.webp',
        imageAlt: 'Llavero Superman',
        price: '$5',
    },
    {
        id: 19,
        name: 'Playera The Flash',
        color: 'Amarillo',
        href: '/404',
        imageSrc: '/shop/imagen19.webp',
        imageAlt: 'Playera The Flash',
        price: '$190',
    },
    {
        id: 20,
        name: 'Sudadera Star Wars',
        color: 'Negro',
        href: '/423',
        imageSrc: '/shop/imagen20.webp',
        imageAlt: 'Sudadera Star Wars',
        price: '$270',
    },
    {
        id: 21,
        name: 'Gorra Spiderman',
        color: 'Rojo',
        href: '/424',
        imageSrc: '/shop/imagen21.webp',
        imageAlt: 'Gorra Spiderman',
        price: '$160',
    },
    {
        id: 22,
        name: 'Calcetines Harry Potter',
        color: 'Gris',
        href: '/425',
        imageSrc: '/shop/imagen22.webp',
        imageAlt: 'Calcetines Harry Potter',
        price: '$70',
    },
    {
        id: 23,
        name: 'Mochila Batman',
        color: 'Negro',
        href: '/426',
        imageSrc: '/shop/imagen23.webp',
        imageAlt: 'Mochila Batman',
        price: '$320',
    },
    {
        id: 24,
        name: 'Pendientes Harry Potter',
        color: 'Plateado',
        href: '/427',
        imageSrc: '/shop/imagen24.webp',
        imageAlt: 'Pendientes Harry Potter',
        price: '$100',
    },
    {
        id: 25,
        name: 'Bufanda Superman',
        color: 'Azul',
        href: '/428',
        imageSrc: '/shop/imagen25.webp',
        imageAlt: 'Bufanda Superman',
        price: '$140',
    },
    {
        id: 26,
        name: 'Taza Batman',
        color: 'Negro',
        href: '/429',
        imageSrc: '/shop/imagen26.webp',
        imageAlt: 'Taza Batman',
        price: '$30',
    },
    {
        id: 27,
        name: 'Llavero Doctor Who',
        color: 'Azul',
        href: '/430',
        imageSrc: '/shop/imagen27.webp',
        imageAlt: 'Llavero Doctor Who',
        price: '$8',
    },
    {
        id: 28,
        name: 'Playera Spiderman',
        color: 'Rojo',
        href: '/431',
        imageSrc: '/shop/imagen28.webp',
        imageAlt: 'Playera Spiderman',
        price: '$230',
    },
    {
        id: 29,
        name: 'Gorra The Flash',
        color: 'Amarillo',
        href: '/432',
        imageSrc: '/shop/imagen29.webp',
        imageAlt: 'Gorra The Flash',
        price: '$170',
    },
    {
        id: 30,
        name: 'Calcetines Star Wars',
        color: 'Negro',
        href: '/433',
        imageSrc: '/shop/imagen30.webp',
        imageAlt: 'Calcetines Star Wars',
        price: '$80',
    },
];
